### ISSUE TITLE
Error converting to String

### ISSUE THREAD

**Issue by bendangelo** [baygeldin/tantiny#21]
Just pulled the repo and getting this error. Using Ruby 3.3.3

Steps:
```
bin/setup
rake build
rake spec
=>
TypeError:                                                                                                                                                
        Error converting to String                                                                                                                              
      # ./lib/tantiny/tokenizer.rb:15:in `__new_stemmer_tokenizer'                                                                                              
      # ./lib/tantiny/tokenizer.rb:15:in `new'                         
```

**Comment by baygeldin** [comment]
The code really does become obsolete very quickly if not supported, huh... I'll try to fix it next week, but I'll be honest, after that I'll probably archive the repo 😢 The project that I'm working on currently doesn't have a use for this gem, and I don't have the spare time to support it.

**Comment by bendangelo** [comment]
No problem. A fix would be much appriciated.

**Comment by baygeldin** [comment]
Okay, so it turned out to be way more complicated than I hoped for, unfortunately. The issue is with the [rutie](https://github.com/danielpclark/rutie) gem that provides Ruby/Rust bindings. Apparently [it doesn't support Ruby 3.x.x](https://github.com/danielpclark/rutie/issues/175), although I haven't found it be the case when running specs on my local machine with Ruby 3.3.3 and Rust 1.76.0. However, when I updated Rust to 1.79.0 and everything broke :/ Again, [seems to be a problem with rutie](https://github.com/danielpclark/rutie/issues/185).

One option is to rewrite the gem to using [magnus](https://github.com/matsadler/magnus) ([example](https://www.hezmatt.org/~mpalmer/blog/2023/04/18/rutie-magnus-rust-extensions-for-ruby.html)), but this will take some effort and I'm not confident that it wouldn't have the same issues with support down the line.

**Comment by bendangelo** [comment]
I'm on Rust 1.79.0. So maybe just update the docs to say only supports Rust 1.76.0.
